CREATE TABLE dbo.Roles(
	Id NVARCHAR(450) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	ConcurrencyStamp NVARCHAR(MAX) NULL,
	[Name] NVARCHAR(256) NULL,
	NormalizedName NVARCHAR(256) NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Roles_DateCreated DEFAULT GETDATE(),
    CreatedBy NVARCHAR(100) NOT NULL,
    DateUpdated DATETIME NULL,
    UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
    DeletedBy NVARCHAR(100) NULL,
	IsDeleted BIT NULL,
    CONSTRAINT PK_Roles PRIMARY KEY CLUSTERED (Id ASC)
);

SELECT * FROM Roles;

CREATE TABLE dbo.AspNetRoleClaims(
	Id INT IDENTITY(1,1) NOT NULL,
	RoleId NVARCHAR(450) NOT NULL,
	ClaimType NVARCHAR(MAX) NULL,
	ClaimValue NVARCHAR(MAX) NULL,
    CONSTRAINT PK_AspNetRoleClaims PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT FK_AspNetRoleClaims_AspNetRoles_RoleId FOREIGN KEY(RoleId) REFERENCES dbo.AspNetRoles (Id) ON DELETE CASCADE
);

SELECT * FROM dbo.AspNetRoleClaims;

CREATE TABLE dbo.Usuarios (
	Id NVARCHAR(450) NOT NULL,
	IdentificationNumber NVARCHAR(MAX) NULL,
	[Name] NVARCHAR(MAX) NULL,
	FirstLastName NVARCHAR(MAX) NULL,
	SecondLastName NVARCHAR(MAX) NULL,
	Active BIT NULL,
	UserName NVARCHAR(256) NULL,
	NormalizedUserName NVARCHAR(256) NULL,
	Email NVARCHAR(256) NULL,
	NormalizedEmail NVARCHAR(256) NULL,
	PasswordHash NVARCHAR(MAX) NULL,
	SecurityStamp NVARCHAR(MAX) NULL,
	ConcurrencyStamp NVARCHAR(MAX) NULL,
 	DateCreated DATETIME NOT NULL CONSTRAINT DF_Usuarios_DateCreated DEFAULT GETDATE(),
    CreatedBy NVARCHAR(100) NOT NULL,
    DateUpdated DATETIME NULL,
    UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
    DeletedBy NVARCHAR(100) NULL,
	IsDeleted BIT NULL,
    CONSTRAINT PK_Usuarios PRIMARY KEY CLUSTERED (Id ASC)
);

SELECT * FROM Usuarios;

CREATE TABLE dbo.AspNetUserClaims(
	Id INT IDENTITY(1,1) NOT NULL,
	UserId NVARCHAR(450) NOT NULL,
	ClaimType NVARCHAR(MAX) NULL,
	ClaimValue NVARCHAR(MAX) NULL,
    CONSTRAINT PK_AspNetUserClaims PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT FK_AspNetUserClaims_AspNetUsers_UserId FOREIGN KEY(UserId) REFERENCES dbo.AspNetUsers (Id) ON DELETE CASCADE
);

SELECT * FROM dbo.AspNetUserClaims;

CREATE TABLE dbo.AspNetUserLogins(
	LoginProvider NVARCHAR(450) NOT NULL,
	ProviderKey NVARCHAR(450) NOT NULL,
	ProviderDisplayName NVARCHAR(MAX) NULL,
	UserId NVARCHAR(450) NOT NULL,
    CONSTRAINT PK_AspNetUserLogins PRIMARY KEY CLUSTERED (LoginProvider ASC, ProviderKey ASC),
    CONSTRAINT FK_AspNetUserLogins_AspNetUsers_UserId FOREIGN KEY(UserId) REFERENCES dbo.AspNetUsers (Id) ON DELETE CASCADE
);

SELECT * FROM dbo.AspNetUserLogins;

CREATE TABLE dbo.AspNetUserTokens(
	UserId NVARCHAR(450) NOT NULL,
	LoginProvider NVARCHAR(450) NOT NULL,
	[Name] NVARCHAR(450) NOT NULL,
	[Value] NVARCHAR(MAX) NULL,
    CONSTRAINT PK_AspNetUserTokens PRIMARY KEY CLUSTERED (UserId ASC, LoginProvider ASC, [Name] ASC),
    CONSTRAINT FK_AspNetUserTokens_AspNetUsers_UserId FOREIGN KEY(UserId) REFERENCES dbo.AspNetUsers (Id) ON DELETE CASCADE
);

SELECT * FROM dbo.AspNetUserTokens;

CREATE TABLE dbo.AspNetUserRoles(
	UserId NVARCHAR(450) NOT NULL,
	RoleId NVARCHAR(450) NOT NULL,
    CONSTRAINT PK_AspNetUserRoles PRIMARY KEY CLUSTERED (UserId ASC, RoleId ASC),
    CONSTRAINT FK_AspNetUserRoles_AspNetRoles_RoleId FOREIGN KEY(RoleId) REFERENCES dbo.AspNetRoles (Id) ON DELETE CASCADE,
    CONSTRAINT FK_AspNetUserRoles_AspNetUsers_UserId FOREIGN KEY(UserId) REFERENCES dbo.AspNetUsers (Id) ON DELETE CASCADE
);

SELECT * FROM dbo.AspNetUserRoles;