CREATE TABLE TiposCliente 
(
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_TiposCliente_Id PRIMARY KEY CLUSTERED (Id ASC),
	Nombre NVARCHAR(250) NULL CONSTRAINT UQ_TiposCliente_Nombre UNIQUE,
    Descripcion NVARCHAR(2000) NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_TiposCliente_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM TiposCliente;

CREATE TABLE Clientes
(
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Clientes_Id PRIMARY KEY CLUSTERED,
    Identificacion NVARCHAR(100) NOT NULL CONSTRAINT UQ_Clientes_Identificacion UNIQUE, 
	Nombre NVARCHAR(250) NULL,
    IdTipoCliente UNIQUEIDENTIFIER CONSTRAINT FK_Clientes_TiposCliente_IdTipoCliente FOREIGN KEY REFERENCES TiposCliente (Id),
    Direccion NVARCHAR(1000) NULL,
    Descripcion NVARCHAR(2000) NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Clientes_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM Clientes;

CREATE TABLE Contratos
(
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Contratos_Id PRIMARY KEY CLUSTERED,
    Identificacion NVARCHAR(100) NOT NULL CONSTRAINT UQ_Contratos_Identificacion UNIQUE,
    IdCliente UNIQUEIDENTIFIER CONSTRAINT FK_Contratos_Clientes_IdCliente FOREIGN KEY REFERENCES Clientes (Id),
    IdArea UNIQUEIDENTIFIER CONSTRAINT FK_Contratos_Areas_IdArea FOREIGN KEY REFERENCES Areas (Id),
    FechaInicio DATETIME NOT NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Contratos_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM Contratos;

CREATE TABLE Proyectos
(
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Proyectos_Id PRIMARY KEY CLUSTERED,
    Nombre NVARCHAR(100) NOT NULL,
    IdArea UNIQUEIDENTIFIER CONSTRAINT FK_Proyectos_Areas_IdArea FOREIGN KEY REFERENCES Areas (Id),
    IdContrato UNIQUEIDENTIFIER CONSTRAINT FK_Proyectos_Contratos_IdContrato FOREIGN KEY REFERENCES Contratos (Id),
    FechaInicio DATETIME NOT NULL,
    FechaFin DATETIME NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Proyectos_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM Proyectos;
