CREATE TABLE Areas (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Areas_Id PRIMARY KEY CLUSTERED (Id ASC),
	Nombre NVARCHAR(250) NULL,
    Descripcion NVARCHAR(2000) NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Areas_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM Areas;

EXEC SP_HELP 'Areas';

CREATE TABLE Modalidades (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Modalidades_Id PRIMARY KEY CLUSTERED (Id ASC),
	Nombre NVARCHAR(250) NULL,
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Modalidades_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM Modalidades;

CREATE TABLE Servicios
(
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Servicios_Id PRIMARY KEY CLUSTERED, 
	Nombre NVARCHAR(250) NOT NULL CONSTRAINT UQ_Servicios_Nombre UNIQUE,
    Descripcion NVARCHAR(2000) NULL,
    IdArea UNIQUEIDENTIFIER CONSTRAINT FK_Servicios_Areas_IdArea FOREIGN KEY REFERENCES Areas (Id),
    IdModalidad UNIQUEIDENTIFIER CONSTRAINT FK_Servicios_Modalidades_IdModalidad FOREIGN KEY REFERENCES Modalidades (Id),
    DateCreated DATETIME NOT NULL CONSTRAINT DF_Servicios_DateCreated DEFAULT GETDATE(),
	CreatedBy NVARCHAR(100) NOT NULL,
	DateUpdated DATETIME NULL,
	UpdatedBy NVARCHAR(100) NULL,
    DateDeleted DATETIME NULL,
	DeletedBy NVARCHAR(100) NULL,
    IsDeleted BIT NULL
);

SELECT * FROM Servicios;